SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS fait_activite;
DROP TABLE IF EXISTS Activite;
DROP TABLE IF EXISTS est_interesse;
DROP TABLE IF EXISTS Interet;
DROP TABLE IF EXISTS Etude;
DROP TABLE IF EXISTS compt_lie_xp;
DROP TABLE IF EXISTS Experience;
DROP TABLE IF EXISTS requiert_compt;
DROP TABLE IF EXISTS Competence;
DROP TABLE IF EXISTS Candidature;
DROP TABLE IF EXISTS Enseignant;
DROP TABLE IF EXISTS contient_contrainte;
DROP TABLE IF EXISTS Contrainte;
DROP TABLE IF EXISTS contient_remarque;
DROP TABLE IF EXISTS Remarque;
DROP TABLE IF EXISTS Poste;
DROP TABLE IF EXISTS Niveau_etudiant;
DROP TABLE IF EXISTS Recruteur;
DROP TABLE IF EXISTS Ecole;

SET FOREIGN_KEY_CHECKS = 1;